"""Remove unique constraint from reviews

Revision ID: c968af156cdc
Revises: f66721e52270
Create Date: 2025-04-29 00:39:46.737303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c968af156cdc'
down_revision = 'f66721e52270'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_movie_review', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_movie_review', ['user_id', 'movie_id'])

    # ### end Alembic commands ###
